require 'rake/testtask'

task :default => :spec
Rake::TestTask.new(:spec) do |t|
  t.libs << 'spec'
  t.pattern = 'spec/**/*_spec.rb'
  t.verbose = false
end

desc 'Console'
task :console do
  require './config/boot'
  require 'pry'
  binding.pry
end